
# This file is part of HemeLB and is Copyright (C)
# the HemeLB team and/or their institutions, as detailed in the
# file AUTHORS. This software is provided under the terms of the
# license in the file LICENSE.

default: 
  CMAKE_BUILD_TYPE: "Release"
  CMAKE_CXX_FLAGS_RELEASE: "-O4"
no_steering:
  HEMELB_STEERING_LIB: "none"
basic_steering:
  HEMELB_STEERING_LIB: "basic"
debug:
  CMAKE_BUILD_TYPE: "Debug"
  HEMELB_LOG_LEVEL: "debug"
  HEMELB_OPTIMISATION: ""
gdb:
  HEMELB_USE_DEBUGGER: "ON"
multiscale:
  HEMELB_BUILD_MULTISCALE: "ON"
no_streaklines:
  HEMELB_USE_STREAKLINES: "OFF"
wait_on_connect:
  HEMELB_WAIT_ON_CONNECT: "ON"
d3q15:
  HEMELB_LATTICE: "D3Q15"
d3q19:
 HEMELB_LATTICE: "D3Q19"
d3q27:
  HEMELB_LATTICE: "D3Q27"
lbgk:
  HEMELB_KERNEL: "LBGK"
entropic_a:
  HEMELB_KERNEL: "EntropicAnsumali"
entropic_c:
  HEMELB_KERNEL: "EntropicChik"
mrt:
  HEMELB_KERNEL: "MRT"
non_newtonian_cy:
  HEMELB_KERNEL: "NNCY"
non_newtonian_cy_mouse:
  HEMELB_KERNEL: "NNCYMOUSE"
non_newtonian_c:
  HEMELB_KERNEL: "NNC"
non_newtonian_tpl:
  HEMELB_KERNEL: "NNTPL"
# Pattern is wall_inlet_outlet
sbb_ladd_nash:
  HEMELB_WALL_BOUNDARY: "SIMPLEBOUNCEBACK"
  HEMELB_INLET_BOUNDARY: "LADDIOLET"
  HEMELB_WALL_INLET_BOUNDARY: "LADDIOLETSBB"
  HEMELB_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_WALL_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSURESBB"
neutral:
  HEMELB_COMPUTE_ARCHITECTURE: "NEUTRAL"
bfl_ladd_nash:
  HEMELB_WALL_BOUNDARY: "BFL"
  HEMELB_INLET_BOUNDARY: "LADDIOLET"
  HEMELB_WALL_INLET_BOUNDARY: "LADDIOLETBFL"
  HEMELB_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_WALL_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREBFL"
bfl_nash_nash:
  HEMELB_WALL_BOUNDARY: "BFL"
  HEMELB_INLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_WALL_INLET_BOUNDARY: "NASHZEROTHORDERPRESSUREBFL"
  HEMELB_WALL_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREBFL"
gzs_ladd_nash:
  HEMELB_WALL_BOUNDARY: "GZS"
  HEMELB_INLET_BOUNDARY: "LADDIOLET"
  HEMELB_WALL_INLET_BOUNDARY: "LADDIOLETGZS"
  HEMELB_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_WALL_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREGZS"
jy_ladd_nash:
  HEMELB_WALL_BOUNDARY: "JUNKYANG"
  HEMELB_INLET_BOUNDARY: "LADDIOLET"
  HEMELB_WALL_INLET_BOUNDARY: "LADDIOLETJY"
  HEMELB_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_WALL_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREJY"
separated_pointpoint:
  HEMELB_POINTPOINT_IMPLEMENTATION: Separated
separated_concerns:
  HEMELB_SEPARATED_CONCERNS: ON
no_debug:
  CMAKE_CXX_FLAGS: "-DNDEBUG"
  CMAKE_C_FLAGS: "-DNDEBUG"
use_sse:
  HEMELB_USE_SSE3: ON
lri_runs:
  HEMELB_WALL_BOUNDARY: "BFL"
  HEMELB_INLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_WALL_INLET_BOUNDARY: "NASHZEROTHORDERPRESSUREBFL"
  HEMELB_WALL_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREBFL"
  HEMELB_KERNEL: "NNCYMOUSE"
microfluidic_device_design:
  HEMELB_WALL_BOUNDARY: "BFL"
  HEMELB_INLET_BOUNDARY: "LADDIOLET"
  HEMELB_WALL_INLET_BOUNDARY: "LADDIOLETBFL"
  HEMELB_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_WALL_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREBFL"
  HEMELB_KERNEL: "NNCYMOUSE"
hemerbc:
  HEMELB_WALL_BOUNDARY: "BFL"
  HEMELB_INLET_BOUNDARY: "LADDIOLET"
  HEMELB_WALL_INLET_BOUNDARY: "LADDIOLETBFL"
  HEMELB_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_WALL_OUTLET_BOUNDARY: "NASHZEROTHORDERPRESSUREBFL"
  HEMELB_KERNEL: "GuoForcingLBGK"
  HEMELB_STEERING_LIB : "none"
  HEMELB_LATTICE: "D3Q19"
  HEMELB_STENCIL: "ThreePoint"
hemerbc_bifurcations:
  HEMELB_WALL_BOUNDARY: "BFL"
  HEMELB_INLET_BOUNDARY: "NASHZEROTHORDERPRESSUREIOLET"
  HEMELB_WALL_INLET_BOUNDARY: "NASHZEROTHORDERPRESSUREBFL"
  HEMELB_OUTLET_BOUNDARY: "LADDIOLET"
  HEMELB_WALL_OUTLET_BOUNDARY: "LADDIOLETBFL"
  HEMELB_KERNEL: "GuoForcingLBGK"
  HEMELB_STEERING_LIB : "none"
  HEMELB_LATTICE: "D3Q19"
  HEMELB_STENCIL: "ThreePoint"
